# AI Lab 11 - Reinforcement Learning
Saad Bin Khalid<br>
20K-0161<br>
BSCS-6F

## **Task 1:** &emsp;  Q Learning Algorithm

In [28]:
# constants

n = 10000
steps = 100
exploration_rate = 1.0

learning_rate = 0.8
discount_rate = 0.95
decay_rate = 0.001


In [29]:
# environment and table

import gym
import numpy as np

env = gym.make('FrozenLake-v1')

n_action = env.action_space.n
n_state = env.observation_space.n
q_table = np.zeros((n_state, n_action))

/usr/local/lib/python3.10/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


In [30]:
# q-learning algorithm

for episode in range(n):
    step = 0
    done = False
    state = env.reset()
    
    for i in range(steps):
        if np.random.uniform(0, 1) > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
        new_state, reward, done, _ = env.step(action)
        
        old_table = q_table[state, action]
        max_val = np.max(q_table[new_state, :])
        q_table[state, action] = old_table + learning_rate * (reward + discount_rate * max_val - old_table)

        state = new_state
        if done == True: break

    exploration_rate = 0.1 + (1 - 0.1) * np.exp(-decay_rate * episode)

env.close()
print(q_table)

[[1.44571684e-01 5.12090208e-02 5.92431519e-02 6.96367552e-02]
 [2.14109782e-02 1.17813923e-02 7.36839420e-03 3.12865125e-02]
 [2.85294596e-02 2.69606625e-02 2.77825533e-02 2.84816380e-02]
 [5.38371922e-03 1.44057552e-03 4.77263438e-03 2.63410013e-02]
 [3.11489435e-01 6.61738536e-02 9.89846004e-03 1.25731747e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.21122564e-05 4.62602491e-01 1.01310904e-02 3.92296755e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.62848383e-02 9.58839286e-03 4.20574458e-02 2.14142117e-01]
 [6.48275482e-02 6.75883425e-01 1.45138127e-02 1.28807686e-03]
 [1.72252013e-02 7.76433230e-01 5.10233486e-04 2.56076726e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [9.84537071e-02 9.19910282e-01 5.85294691e-01 9.27152773e-02]
 [6.31107987e-01 7.18582253e-01 6.48179852e-01 9.99599684e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.000000

## **Task 2:** &emsp;  Smart Cab's Job

In [32]:
# constants

n = 1000
steps = 99
exploration_rate = 1.0

learning_rate = 0.7
discount_rate = 0.9
decay_rate = 0.001

In [48]:
# environment

import os
import gym
import pygame
import random
import numpy as np

os.environ['SDL_VIDEODRIVER']='dummy'
pygame.display.set_mode((640,480))
env = gym.make('Taxi-v3')

n_action = env.action_space.n
n_state = env.observation_space.n
q_table = np.zeros((n_state, n_action))

/usr/local/lib/python3.10/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


In [49]:
# q learning algorithm

for episode in range(n):
    done = False
    state = env.reset()

    for i in range(steps):
        if np.random.uniform(0, 1) > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()            
        new_state, reward, done, _ = env.step(action)

        old_table = q_table[state, action]
        max_val = np.max(q_table[new_state, :])
        q_table[state, action] = old_table + learning_rate * (reward + discount_rate * max_val - old_table)

        state = new_state
        if done == True: break

    exploration_rate = np.exp(-decay_rate * episode)

In [50]:
# execution

rewards = 0
done = False
state = env.reset()
print("state:")
print(state)

for i in range(steps):
    action = np.argmax(q_table[state,:])
    new_state, reward, done, _ = env.step(action)
    rewards += reward
    env.render()

    print(i+1, ") score: ", rewards)
    state = new_state
    if done == True: break

state:
114
1 ) score:  -1
2 ) score:  -2
3 ) score:  -3
4 ) score:  -4
5 ) score:  -5
6 ) score:  -6
7 ) score:  -7
8 ) score:  -8
9 ) score:  -9
10 ) score:  -10
11 ) score:  -11
12 ) score:  -12
13 ) score:  -13
14 ) score:  -14
15 ) score:  6
